### ISSUE TITLE
How could you know the CRC16 algorithm of ATSHA204?

### ISSUE THREAD

**Issue by Terminus-IMRC** [cryptotronix/atsha204-i2c#16]
Hello.

This is actually not an issue, but could you please tell me how could you know the CRC16 algorithm of ATSHA204? The algorithm is not a common one and I was struggling with it.

**Comment by jbdatko** [comment]
The polynomial is listed in the datasheet. But then you have to account for
the endianess when preparing it.

**Comment by Terminus-IMRC** [comment]
How did you know it? Trials and errors?

**Comment by jbdatko** [comment]
No, it was in the datasheet.

**Comment by Terminus-IMRC** [comment]
Oh, sorry. Thank you!
